const listaDeLivros = [
{id: 1, titulo: "Dom Casmurro", ano: 1899, disponivel: true},
{
id: 2,
titulo: "Memórias Póstumas de Brás Cubas",
ano: 1881,
disponivel: true,
},
{id: 3, titulo: "O Cortiço", ano: 1890, disponivel: true, exemplares: 10},
{id: 4, titulo: "Iracema", ano: 1865, disponivel: true, exemplares: 10},
{id: 5, titulo: "Vidas Secas", ano: 1938, disponivel: true, exemplares: 10},
{
id: 6,
titulo: "Capitães da Areia",
ano: 1937,
disponivel: true,
exemplares: 10,
},
{id: 7, titulo: "Senhora", ano: 1875, disponivel: true, exemplares: 10},
{
id: 8,
titulo: "A Hora da Estrela",
ano: 1977,
disponivel: true,
exemplares: 10,
},
{id: 9, titulo: "Macunaíma", ano: 1928, disponivel: true, exemplares: 10},
{
id: 10,
titulo: "O Auto da Compadecida",
ano: 1955,
disponivel: true,
exemplares: 10,
},
{
id: 11,
titulo: "Quincas Borba",
ano: 1891,
disponivel: true,
exemplares: 10,
},
{id: 12, titulo: "Sagarana", ano: 1946, disponivel: true, exemplares: 10},
{
id: 13,
titulo: "Claro Enigma",
ano: 1951,
disponivel: true,
exemplares: 10,
},
{
id: 14,
titulo: "A Moreninha",
ano: 1844,
disponivel: true,
exemplares: 10,
},
{
id: 15,
titulo: "Triste Fim de Policarpo Quaresma",
ano: 1915,
disponivel: true,
exemplares: 10,
},
];
export {listaDeLivros};